#!/usr/bin/env node
import config from './config.js';
import fs from 'node:fs';
import {
  getRecords, downloadVideo, downloadTranscript, downloadChatLog,
  readTranscriptSync, readChatLogSync, generateSummary, generateIrcLog,
  scribe2GenerateHtml, uploadToArchive, emailSummary
} from './lib/google-apps.js';
import moment from 'moment';
import path from 'node:path';
import process from 'process';
import {Command} from 'commander';

// name of the cache file
const CACHE_FILENAME = 'cache.json';

// create the CLI and parse the options
const program = new Command();
program
  .option('-d, --date <YYYY-MM-DD>',
    'Meeting date to process', moment().format('YYYY-MM-DD'))
  .option('-e, --email',
    'Send summary email', false)
  .option('-t, --to <email>',
    'E-mail address to send summary email to', false)
  .option('-u, --upload',
    'Upload to archive server', false)
  .parse(process.argv);
const options = program.opts();

let date = (options.date) ?
  moment(options.date).format('YYYY-MM-DD') : moment().format('YYYY-MM-DD');

// load secrets from the environment
config.geminiApiKey = process.env.GEMINI_API_KEY;
config.archive.privateKey = process.env.ARCHIVE_SSH_KEY;
config.googleApiOauth2Token = process.env.OAUTH2_TOKEN;

let meetingsFound = false;
for(let meeting of config.meetings) {
  meeting.slug = meeting.name.toLowerCase().replaceAll(' ', '-');
  // get record for meeting and date
  let record = await getRecords({meeting, date, config});
  if(!record.transcript) {
    continue;
  } else {
    console.log(`Archiving ${meeting.name} meeting for ${date}...`);
    meetingsFound = true;
  }

  // download the video recording
  const videoFilename = path.join(
    config.logDir, `${config.community}-${meeting.slug}-${date}.mp4`);
  if(!fs.existsSync(videoFilename)) {
    const videoStream = fs.createWriteStream(videoFilename);
    await downloadVideo({
      fileStream: videoStream,
      driveLocation: record.recording.driveDestination,
      config
    });
  } else {
    console.log('  - Video already downloaded (video/mp4).');
  }

  // upload the video recording to the archive
  if(options.upload && fs.existsSync(videoFilename)) {
    const videoFileStream = fs.createReadStream(videoFilename);
    await uploadToArchive({
      fileStream: videoFileStream,
      filename: path.basename(videoFilename),
      config
    });
    console.log('  - Uploaded video to archive (video/mp4).');
  }

  // write .log transcript
  const logTranscriptFilename = path.join(config.logDir,
    `${config.community}-${meeting.slug}-${date}-transcript.log`);
  if(!fs.existsSync(logTranscriptFilename)) {
    const logFileStream = fs.createWriteStream(logTranscriptFilename);
    await downloadTranscript({
        mediaType: 'text/plain',
        docLocation: record.transcript.docsDestination,
        fileStream: logFileStream,
        config
      });
  } else {
    console.log('  - Text transcript already downloaded (text/plain).');
  }

  // upload the .log transcript to the archive
  if(options.upload && fs.existsSync(logTranscriptFilename)) {
    const logFileStream = fs.createReadStream(logTranscriptFilename);
    await uploadToArchive({
      fileStream: logFileStream,
      filename: path.basename(logTranscriptFilename),
      config
    });
    console.log('  - Uploaded text transcript to archive (text/plain).');
  }

  // write .md transcript
  const mdTranscriptFilename = path.join(config.logDir,
    `${config.community}-${meeting.slug}-${date}-transcript.md`);
  if(!fs.existsSync(logTranscriptFilename)) {
    const mdFileStream = fs.createWriteStream(mdTranscriptFilename);
    await downloadTranscript({
      mediaType: 'text/markdown',
      docLocation: record.transcript.docsDestination,
      fileStream: mdFileStream,
      config
    });
  } else {
    console.log('  - Text transcript already downloaded (text/markdown).');
  }

  // upload the .md transcript to the archive
  if(options.upload && fs.existsSync(mdTranscriptFilename)) {
    const logFileStream = fs.createReadStream(mdTranscriptFilename);
    await uploadToArchive({
      fileStream: logFileStream,
      filename: path.basename(mdTranscriptFilename),
      config
    });
    console.log('  - Uploaded text transcript to archive (text/markdown).');
  }

  // write chat log
  const chatLogFilename = path.join(config.logDir,
    `${config.community}-${meeting.slug}-${date}-chat.log`);
  if(!fs.existsSync(chatLogFilename)) {
    const logFileStream = fs.createWriteStream(chatLogFilename);
    await downloadChatLog({
        mediaType: 'text/plain',
        docLocation: record.chatlog.docsDestination,
        fileStream: logFileStream,
        config
      });
  } else {
    console.log('  - Chat log already downloaded (text/plain).');
  }

  // generate .html transcript (scribe2)
  const htmlTranscriptFilename = path.join(config.logDir,
    `${config.community}-${meeting.slug}-${date}.html`);
  if(meeting.scribe2 && !fs.existsSync(htmlTranscriptFilename)) {
    const transcript =
      await readTranscriptSync({transcriptFilename: logTranscriptFilename});
    const chatLog =
      await readChatLogSync({chatLogFilename});

    // generate IRC log
    const ircLogFilename = path.join(config.logDir,
      `${config.community}-${meeting.slug}-${date}-irc.log`);
    const ircLog = await generateIrcLog({
      config, meeting, date, transcript, chatLog
    });
    fs.writeFileSync(ircLogFilename, ircLog);

    console.log("TRANSCRIPT", transcript, "CHAT", chatLog);
    // generate HTML
    const htmlTranscript = await scribe2GenerateHtml({ircLogFilename});

    fs.writeFileSync(htmlTranscriptFilename, htmlTranscript);
    console.log(`  - HTML archival complete (text/html).`);
  } else {
    console.log('  - HTML transcript already generated (text/html).');
  }

  // upload the .html transcript to the archive
  if(options.upload && fs.existsSync(htmlTranscriptFilename)) {
    const logFileStream = fs.createReadStream(htmlTranscriptFilename);
    await uploadToArchive({
      fileStream: logFileStream,
      filename: path.basename(htmlTranscriptFilename),
      config
    });
    console.log('  - Uploaded HTML transcript to archive (text/html).');
  }

  if(options.email) {
    // get the transcript
    const transcript =
      await readTranscriptSync({transcriptFilename: mdTranscriptFilename});

    // generate and email meeting summary
    if(transcript.length > 100) {
      let email = options.to || meeting.email;
      const summary =
        await generateSummary({meeting, date, transcript, config});
      await emailSummary({meeting, email, date, summary, transcript, config});
      console.log(`  - Sent email to ${email}`);
    } else {
      console.error('Error: Failed to summarize empty transcript.');
    }
  }
}

if(!meetingsFound) {
  console.log(`No meetings to archive found for ${date}.`);
}
